// examples/react-app/src/App.tsx
import { useState } from "react";
import { autometrics, init } from "autometrics";
import "./App.css";

init({ pushGateway: "http://0.0.0.0:8080/metrics" });

type Post = {
  userId: number;
  id: number;
  title: string;
  body: string;
};

let posts: Array<Post>;

async function allPosts() {
  if (!posts) {
    try {
      const res = await fetch("https://jsonplaceholder.typicode.com/posts");
      const data = await res.json();
      posts = data;
    } catch (err) {
      throw new Error(`API call error: ${err}`);
    }
  }
  return posts;
}

const getRandomPost = autometrics(
  {
    functionName: "getRandomPost",
    moduleName: "App",
  },
  async () => {
    const rand = Math.floor(Math.random() * 100 + 1);
    const posts = await allPosts();
    console.log(posts[rand]);
    return posts[rand];
  },
);

function App() {
  const [post, setPost] = useState<Post>();

  const handleClick = async () => {
    try {
      const data = await getRandomPost();
      setPost(data);
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <div className="App">
      <h1>Post getter</h1>
      <div className="card">
        <button onClick={handleClick}>Get post</button>
        <div>
          {post ? (
            <div>
              <h2>{post.title}</h2>
              <p>{post.body}</p>
            </div>
          ) : (
            <p />
          )}
        </div>
      </div>
    </div>
  );
}

export default App;

// examples/svelte-app/src/App.svelte
<script lang="ts">
  import { init } from "autometrics";
  import { autometrics } from "autometrics";
  init({ pushGateway: "http://0.0.0.0:8080/metrics" });

  let promise: Promise<any>;

  const getWow = autometrics(
    {
      functionName: "getWow",
      moduleName: "MODULE",
    },
    async () => {
      const res = await fetch(
        "https://owen-wilson-wow-api.onrender.com/wows/random"
      );
      return await res.json();
    }
  );

  async function handleClick() {
    promise = getWow();
  }
</script>

<main>
  <div class="card">
    <div>
      <button on:click={handleClick}>GET WOW</button>

      <div>
        {#await promise then data}
          <pre>{JSON.stringify(data)}</pre>
        {/await}
      </div>
    </div>
  </div>
</main>
